sudo: false
dist: trusty
language: java
jdk:
  - openjdk10
  - oraclejdk10
before_install:
  - rm ~/.m2/settings.xml || true 
  - ulimit -c unlimited -S
  - mvn -N io.takari:maven:wrapper
after_success:
  - bash .travis_after_success.sh
cache:
  directories:
    - $HOME/.m2

env:
  global:
    # CI_DEPLOY_USERNAME
    - secure: "hUi5tkUawH2tLBnl6Yir88UmwYcNVyK35BVUuGRPABSzf6upb/7sde4YOB1owPVwwsJcyWYQoqhi/wXSC/Z89foIZXddzA7u8YAOBtEAzCJFTpyi7NBeGVJcoI8aHDbqL/872bV7wBvEaL2hlnKJVf01TcV6/qo1Cq3OPoENplw2ff/aIGCNoLcqnpdDdeYSySob8OXMyOiTXQh90S2lptUrR81mLBv88YJchdDhYWhHLYtqdb1cmfDS97tvl+gFqpWioRzdAhfeDUzkTaAx/eJsuok8YeX1WDvds/iOc/HLOc/MQ7pqbUYvCGFEZOE6WmOSWc2QSIUu8/R/6yU/g9ZybcsgzLH73Mxwl4U5yabzn/9uJ22tOB+DwigkOsJLtzYBLC9+3vnlRVKMvLvE7WC19mqINqUmuWAFysQ8Hgvl+MP+gBfzgmnDt/R/0cyD4m4aUb0aROYT0eTfYmHPH4tUONmm4W7lrch4JDvzrMRD1BA80kT9ReSn1CAPOb2ZoGGRX41gOKZMMx23J1Hd8SEZ8TCyUjACcFB82dn1mJSS3eK2xPsgsjfnBX/JeOQdRombpvSPLh64E/Pg+40e06RMQoXw+99J7MXEndQKcwGP/BQE0azHH21T+op5NNA+JbL6o55u5aLYtxvMDFfir84P/BU5r71ATCr5pF3LbXQ="
    # CI_DEPLOY_PASSWORD
    - secure: "GxU6rNynkEiNaJRAZBNI/39NsCPdIUE8JD0FiQh2sffa5ME22H47+py3jCxieAuRvOqVN6WkDc6maL6a1Bs0rTR05OZw7wzKaiOnn/OxbBlTCjJVr1wdZEHs5yGmSR09KtnR0pHXJOkEM1uBHXNSIRyC0eU4t/yw1RqJNYC/XA4g/N8/cCApKVaz4+7NKbIX7P1bQ/VVBj7s/iDmxUN9iT1IxkQMkE6su8SrM7nGH17WHq2Dq4CRJqv3IJcd4mNE17UEBIurwvJz4J6z8TZePTx3vgI3VwyD/sIJOqo6aOZr5yMrrtpeujefWO7fwHMZYaUa6BAKgenqy6m5/Pt6gbArFqki1IrsnG59mxH3o+3ElsWU6c+ybjMkn/lOsROcCZU68t78G8rY1enmUHkOLw5zDrZYT5WsWn4pd0UmGgGS1beT2Rv2rlQ8FfPDT7m3fvLYQ7DU256v4cM6m1y20SWMaOr+rWo69iEzr0cDVNGzCjozbycOQv8xZ9lmVpqs8YLlq6RkwpGWHdFVJKCFD4APiKJRRyjvCdcqo2yuiWpa8LS5sUGFxJr70Byzu7w/3pK08Je9SGM97ZZpGqwn38q6NuSWshA0oWXIjSd0CFpEUov1L1OVqSKTO5D6xS1KrmZO2bkQekhHf9wpptXbpOipOfQNhRRRW03hTTyc1J0="
