template: ${helloworld/template:-Hello, %s!}
defaultName: ${helloworld/defaultName:-Stranger}

# Atomix-specific options.
atomix:
  localNode:
    id: node1
    endpoint: 127.0.0.1:10000
    type: data
  bootstrapNodes:
    - id: node1
      endpoint: 127.0.0.1:10000
    - id: node2
      endpoint: 127.0.0.1:10001
    - id: node3
      endpoint: 127.0.0.1:10002
  dataDirectory: ./data1

# HTTP-specific options.
server:

  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 0

  requestLog:
    appenders:
      - type: console
        timeZone: UTC
        target: stdout

logging:
  level: INFO
  loggers:
    com.smoketurner.dropwizard.atomix: DEBUG
    com.example.helloworld: DEBUG
    io.atomix: INFO
  appenders:
    - type: console
      timeZone: UTC
      target: stdout
